### ISSUE TITLE
Provide a list of stats that will be provided for each Real Game

### ISSUE THREAD

**Issue by wrburgess** [wrburgess/league-server#12]
I'm gathering that you'll be providing a flat file or json document that has each players stat line for each game. Since college baseball players split time at pitching and hitting, we should probably just have a single record, per player, per game. I don't care if you provide stats now, I just want to know which fields to set up.

**Comment by caelon** [comment]
I think it makes sense to me to have a set of non-pitching and a set of
pitching. Here's what appears to be available.

Non-pitching:
AB
R
H
RBI
K (as a hitter)
BB
2B
3B
HR
HBP
SH
SF
SB
E (as a fielder)
PB (passed ball, count as an error?)

Pitching:
IP
H
R
ER
BB
K (as a pitcher)
WP
BK
IBB
AB
BF (batters faced)
GO (??) (ground outs)
FO (??) (fly outs)

# Pitches (??)

W
L
SV

## 

Don
T: 407-588-7224

**Comment by wrburgess** [comment]
But why manage two tables if players can earn both hitting and pitching
stats in the same game?

rb (on mobile)

On Oct 21, 2012, at 12:48 PM, Don VanDemark notifications@github.com
wrote:

I think it makes sense to me to have a set of non-pitching and a set of
pitching. Here's what appears to be available.

Non-pitching:
AB
R
H
RBI
K (as a hitter)
BB
2B
3B
HR
HBP
SH
SF
SB
E (as a fielder)
PB (passed ball, count as an error?)

Pitching:
IP
H
R
ER
BB
K (as a pitcher)
WP
BK
IBB
AB
BF (batters faced)
GO (??) (ground outs)
FO (??) (fly outs)

# Pitches (??)

W
L
SV

## 

Don
T: 407-588-7224

On Sat, Oct 20, 2012 at 5:12 PM, Randy Burgess notifications@github.comwrote:

> I'm gathering that you'll be providing a flat file or json document that
> has each players stat line for each game. Since college baseball players
> split time at pitching and hitting, we should probably just have a single
> record, per player, per game. I don't care if you provide stats now, I
> just
> want to know which fields to set up.
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/wrburgess/league-server/issues/12>.

—
Reply to this email directly or view it on
GitHubhttps://github.com/wrburgess/league-server/issues/12#issuecomment-9645420.

**Comment by caelon** [comment]
I don't have any concrete reason besides it just feeling right. You're
talking about 80-90% of the records having a bunch of fields with null or

## zero entries for those that don't pitch and hit in the same game.

Don
T: 407-588-7224

**Comment by wrburgess** [comment]
Well, I don't care about nulls or zeros, really. I care about not having to
access two tables for the same logic.

A stat is a stat, regardless if it's zero or not.

Not to mention that fewer records in a db is a good thing. Performance
isn't really impacted by a lot of fields on the same record. You're talking
about two records per game per player.

rb

rb@jbrb.com

**Comment by caelon** [comment]
No, I'm talking about two records per game for, at most, 20% of the
players. Doesn't width (# of fields) of a table affect performance? In

## other words, why carry the extra weight for the benefit 20% of the players?

Don
T: 407-588-7224

**Comment by caelon** [comment]
I didn't think about needing to hit both tables for every player, whether

## there's a record for them or not. You're probably right on one table.

Don
T: 407-588-7224

**Comment by wrburgess** [comment]
Yeah, it's more about joins, multiple calls, managing a two classes that do the same thing, etc. To me, a nil or zero is still a relevant stat. 

Also, the fact that college players can earn stats for both hitting and pitching in the same game (more often than in MLB) means we'll have to always check if all stats are present. Might as well manage stats all in one place.

**Comment by caelon** [comment]
## Yeah, the second point was the one I can be convinced by. One table it is.

Don
T: 407-588-7224
